name: Nightly Job

on:
  schedule:
    # Runs every 24 hours
    - cron: '0 0 * * *'
  # This can be used to allow manually triggering nightlies from the web interface
  workflow_dispatch:

jobs:
  nightly-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python generate_github_contributions_report.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}

      - name: Configure Git
        run: |
          git config --global user.name 'Nihal Jain'
          git config --global user.email 'nihaljain.cs@gmail.com'

      - name: Commit and push changes
        run: |
          git add output/*
          git commit -m "Update output files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      # See https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot
      contents: write